title: ID.BLOG
author: azhar-basyiri
subtitle: Manusia Yang Terlupakan

url: "http://id.basyiri.my.id"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://basyiri.my.id"
footer_text: "Azhar Basyiri Hartono"

favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Tentang"
   absolute-link: "https://basyiri.my.id/id"
 - name: "Radio"
   absolute-link: "https://basyiri.my.id/auditorium"
 - name: "Fave"
   absolute-link: "https://azhar.basyiri.my.id"

future: true
